server:
  port: 8084
spring:
  application:
    name: reproduction-simulator-service
simulator:
  default-scenario: ${SIMULATOR_DEFAULT_SCENARIO:SIMPLE_AND}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
